### ISSUE TITLE
Higher version number

### ISSUE THREAD

**Issue by dra27** [ocaml/graphics#1]
Note https://github.com/ocaml/opam-repository/pull/12674/ which is blocked only by a CI issue and once that's fixed will be wanted. Can we pick a higher initial release number - is there anything prevent 5.0?

**Comment by dra27** [comment]
Or 4.09.0, for that matter 🙂

**Comment by diml** [comment]
That seems fine to me. Thinking about it again, we should probably not make this package available for OCaml < 4.09, otherwise there will be a conflict for the ownership of file `graphics/META`, i.e. both ocamlfind and this package might try to install it :/

**Comment by dra27** [comment]
Indeed - but once that opam-repository PR is sorted, the package becomes uniformly installable with `opam install graphics`, so that seems OK!

**Comment by diml** [comment]
It's just that we have a problem if we install things in this order:

1. ocaml < 4.09
2. ocamlfind
3. graphics (this repo)

in this case, ocaml will install `<stdlib-dir>/graphics.cma`. Because of this, ocamlfind will install `<libdir>/graphics/META`. graphics will also install `<libdir>/graphics/META` because that's what it always does: BOOM.

It feels safer to simply wait for 4.09 and release this repo with a `>= 4.09` lower bound.

**Comment by dra27** [comment]
I agree - all I meant was to release with a version number that's definitely bigger than the graphics.4.08.0 which will hopefully by then be in opam-repository.

**Comment by dra27** [comment]
The opam-repository PR is merged. As it happens, you can build later versions of graphics with older compilers (I seem to remember finding that OCaml 3.07 could actually compile the 4.06.0 graphics library!) but for opam-repository I elected to have it that you always get the version of graphics which matches the compiler, just for the "least surprise" principle.

So when 4.08.0 is released, I'll do an update on opam-repository for graphics.4.08.0 and then when 4.09.0 comes out we can release this package as graphics.4.09.0 with the an `ocaml >= "4.09.0"` constaint.

**Comment by diml** [comment]
That works for me!

**Comment by diml** [comment]
I updated the changelog to be sure to use the right number when release time comes

**Comment by xavierleroy** [comment]
The latest release is numbered 5.0.0, so I guess this report served its purpose and can be closed now.
