### ISSUE TITLE
release graphics in opam for ocaml 4.09.0

### ISSUE THREAD

**Issue by hhugo** [ocaml/graphics#12]

**Comment by diml** [comment]
@dra27 do you remember what version we said we would use for graphics? IIRC, it's 5.0.0 since graphics is not tied to the compiler internals

**Comment by dra27** [comment]
In #11 I put 4.09.0, but it could be either. We could call it 4.09 and then bump it to 5 if there are (ever any) changes?

I’m fairly sure I have an opam-repository branch already done for it - I’ll check in a bit and push it

**Comment by dra27** [comment]
(It’s obviouskt *not* a straight copy of the 4.08.1 one!)

**Comment by garrigue** [comment]
This may not be the place to discuss that, but labltk relies on the ocaml configuration to detect X11. How can we factor the logic, both in and out of opam?

**Comment by dra27** [comment]
For opam, it’s done via the conf-libX11 package. I haven’t looked in detail at what Jérémie’s done with the Dune port here

**Comment by diml** [comment]
I'm tempted to call it 5.0.0 and switch to semantic versioning at the same time, just to avoid confusion.

For X11, I made graphics depend on `conf-libX11`. No special compilation flags are used and the following link flags are used:
- `os_type = Win32` -> `-lkernel32 -lgdi32 -luser32`
- otherwise -> `-lX11`

BTW, what authors should we put in the opam file? I put only @xavierleroy for now.

**Comment by dra27** [comment]
See https://github.com/dra27/opam-repository/blob/graphics-4.09/packages/graphics/graphics.4.09.0/opam

**Comment by dra27** [comment]
I'm inclined to agree with calling it 5.0.0 - although it feels strange to bump the major version with no changes, it will also feel strange to be using semver and having 4.09.1, 4.10.0 before OCaml does!

**Comment by dra27** [comment]
(I can redo that opam-repository PR once there's a tag and a confirmed version number)

**Comment by diml** [comment]
Let's go for 5.0.0. @dra27 do you have a PR already prepared for this? I was planning to use `dune-release` to proceed with the release

**Comment by diml** [comment]
I created the release on github. @dra27 let me know if I should proceed with the opam-repository PR

**Comment by dra27** [comment]
I just diff'd the graphics.opam with the one I'd done by hand: the only difference is that I added Jun Furuse, J-M Geffroy, Jacob Navia and Pierre Weis to the authors list (I think that was based on everyone whose name appears in a copyright header). I'm just old-school with the opam files - I'd add those files and use `dune-release` :)

**Comment by diml** [comment]
Alright, I added the other authors and made the release: https://github.com/ocaml/opam-repository/pull/14828
