### ISSUE TITLE
Does this library work for the Windows Linux Subsystem?

### ISSUE THREAD

**Issue by awang9999** [ocaml/graphics#21]
I successfully installed graphics and tried to run 
`open_graph ""`
and obtained the following error:
`Graphic_failure "Cannot open display ".`

I'm running OCaml and Opam in the windows Linux subsystem.

**Comment by nojb** [comment]
OCaml (and OPAM) installed in WSL works pretty much as on any other Unix distribution. In particular, you will probably need to install an X server in order to work with GUI programs.

**Comment by awang9999** [comment]
Yep, that did the trick. My default window is now just appearing and instantly disappearing. Any insights on that? Sorry, if this no longer pertains to the issue I initially raised.

**Comment by nojb** [comment]
> Yep, that did the trick. My default window is now just appearing and instantly disappearing. Any insights on that? Sorry, if this no longer pertains to the issue I initially raised.

Are you doing anything after creating the `Graphics` window? If not, the program will terminate right away and take down the window with it.

For example, you can call `Graphics.read_key` to block until a key is pressed.

**Comment by awang9999** [comment]
Understood. Thank you so much for the rapid and helpful response!
