### ISSUE TITLE
Cannot build graphics 5.0.1 on Linux

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [ocaml/graphics#24]
I was trying to build ocaml-graphics for my system using the AUR package. What it does is downloading the source package, extract it, and run `dune build -p graphics` in it. It fails with the following error message:
```
    ocamlopt src/discover/discover.exe (exit 2)
(cd _build/default && /usr/bin/ocamlopt.opt -w -40 -g -o src/discover/discover.exe /usr/lib/ocaml/unix.cmxa -I /usr/lib/ocaml /usr/lib/ocaml/dune-configurator/configurator.cmxa src/discover/.discover.eobjs/native/discover.cmx)
File "_none_", line 1:
Error: Files /usr/lib/ocaml/dune-configurator/configurator.cmxa
       and /usr/lib/ocaml/stdlib.cmxa
       make inconsistent assumptions over implementation Stdlib__sys
Done: 81/107 (jobs: 1)
```
Compiling the 5.0.0 sources yields no error.

**Comment by dra27** [comment]
I think this is a packaging error - https://www.archlinux.org/packages/community/x86_64/dune/ was built before https://www.archlinux.org/packages/extra/x86_64/ocaml/

**Comment by dra27** [comment]
5.0.0 wouldn't have this problem since it doesn't use configurator (see #17)

**Comment by dra27** [comment]
This should have been fixed downstream - see [AUR bug tracker ticket 67923](https://bugs.archlinux.org/task/67923?string=dune&project=5&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=)
