### ISSUE TITLE
License exception may need an update

### ISSUE THREAD

**Issue by paurkedal** [ocaml/graphics#26]
The linkage exception in the LICENSE file refers to "OCaml Core System", which I presume originates from a time when the graphics library was distributed with the OCaml compiler.

**Comment by dra27** [comment]
`LICENSE` begins:
https://github.com/ocaml/graphics/blob/2ad892d338d7fcd9bf5938b1070bf939491dca75/LICENSE#L1-L2

which I think remains unambiguous, if somewhat dated. I think it better to leave it as-is, therefore.

**Comment by paurkedal** [comment]
Okay, I was just worried it was overlooked.
