### ISSUE TITLE
opam install graphics fail on windows.

### ISSUE THREAD

**Issue by brunomorvan** [ocaml/graphics#32]
It seems that the last sources https://github.com/ocaml/graphics/tree/master/src/win32
are not  imported by "opam install graphics"  (Windows 10)

the diff https://github.com/ocaml/graphics/commit/3da77239e412c20780751e7de935b68448d10de0 is not applied,
and lead to " multiple definition of `grremember_mode' " error.

I use the last versions of opam(2.0.7) and ocaml(4.11.1) installed  by https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/OCaml64.exe 
and graphics (5.1.0) .

**Comment by dra27** [comment]
I just released Graphics 5.1.1 to opam-repository (see https://github.com/ocaml/opam-repository/pull/18072).

In the meantime, `opam pin add graphics --dev-repo` should work too.

**Comment by brunomorvan** [comment]
Thanks for reactivity. It works now !!
