### ISSUE TITLE
Mac: Fatal error: exception Graphics.Graphic_failure("Cannot open display ")

### ISSUE THREAD

**Issue by mindlid** [ocaml/graphics#44]
When trying to run an example build from dune got:
![Screenshot 2023-01-31 at 12 49 03](https://user-images.githubusercontent.com/19735362/215867394-1001ab1d-a5aa-4132-b7ec-02d2ed58c848.png)

Xlib.h it's installed at `/opt/X11/include/X11/Xlib.h`

![Screenshot 2023-01-31 at 12 51 51](https://user-images.githubusercontent.com/19735362/215867759-1930cf75-c1e3-49ca-9e96-5f1a584a3fb7.png)

Using M1 Mac with Ventura

**Comment by xavierleroy** [comment]
You need an X11 server to run X11 applications.  Try to install XQuartz: https://www.xquartz.org/

**Comment by mindlid** [comment]
@xavierleroy they were already installed just restarted and it worked
